### ISSUE TITLE
大佬，压缩文件有密码，可以提供吗？

### ISSUE THREAD

**Issue by AidBitCat** [ChowLiang2000/Stable-Diffusion-WebUI-#1]
![%%Y9~JJ$YZZ1{8RXK}ZFO@X](https://github.com/ChowLiang2000/Stable-Diffusion-WebUI-/assets/18436766/b39a7ee8-9b3d-435d-baff-6ab4a9fdb261)

**Comment by AidBitCat** [comment]
弄到了，不用了~

**Comment by leangjia** [comment]
解压密码
bilibili-秋葉aaaki
